#DO NOT CHANGE THIS VALUE!
config-version: '2.1.0'
# When a player unlocks a container, should the protection be removed (true) or should the protection be transfered to the player with the key (false)
remove-protection: true
# Should it be, since a chest ist last accessed by any person (including Admin), or since the Owner has been online.
since-owner-online: true
# displayname: Name of the Item
# Material: ItemType.
# Lore: Small text below the item, when hovering in Inventory
# Enchantments: Enchantments which can be added to said item.
# Time: Amount of item, since accessed or owner online.
keys:
  bronze:
    #Displayname of the key | If you wish to not have a custom displayname please set the value to '', never leave it completely empty
    displayname: '&aLWCKey'
    #Please use these to choose your material, it's a list of them: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    #Manditory setting
    material: TRIPWIRE_HOOK
    #Lore of the key
    #If you don't want to use a lore, leave the values empty by having NOTHING after the line ( - ), if you wish to skip a line set the value to ''
    lore:
      - '&5Hello'
      - ''
      - '^ Skip A Line LOL!'
      -
    #Please use these to choose your enchantment, it's a list of them, only take the field value: i.e 'ARROW_DAMAGE': https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
    #If you don't want to use an enchantment, leave the values empty by having NOTHING after the line ( - )
    enchantments:
      - 'Durability,5'
      - 'ARROW_Damage,2'
    # Time since last accessed or since the owner has been online (configurable above). Valid: 'd' Day ,'h' hours ,'s' seconds ,'w' weeks, 'y' years.
    # If you wish to disable this, so keys will always work regardless set the value to ''
    time: '2 hours'
  platinum:
    displayname: '&7&lPlatinum Key'
    material: STONE
    lore:
      - '&6&lThis is a platinum Key'
      - '&8&lYou can configure me on the config!'
      -
    enchantments:
      - 'Durability,3'
      - 'Arrow_Damage,4'
    time: '2 minutes'
