#DO NOT CHANGE THIS VALUE!
config-version: '1.3.0'
# When a player unlocks a container, should the protection be removed (true) or should the protection be transfered to the player with the key (false)
remove-protection: true
#Displayname of the key
displayname: '&aLWCKey'
#Please use these to choose your material, it's a list of them: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
material: TRIPWIRE_HOOK
#Lore of the key
#If you don't want to use a lore or want to skip a line, leave the values empty by having NOTHING after the line ( - )
lore:
  - 'Hello!'
  - '' # No Lore on the second line NOTE: This line will be shown, but empty
  - #This lore line won't exist
  -

#Please use these to choose your enchantment, it's a list of them, only take the field value: i.e 'ARROW_DAMAGE': https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
#If you don't want to use an enchantment, leave the values empty by having NOTHING after the line ( - )
enchantments:
  - 'DURABILITY,5'
  - 'ARROW_DAMAGE,2'
  - #No Enchantment
  - 'THORNS,3'
# - 'KNOCKBACK,2'